[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "../functions"

[build.environment]
  NODE_VERSION = "18"

[dev]
  command = "npm run dev"
  targetPort = 3000
  publish = ".next"
  framework = "nextjs"